version: "2"
services:
  app: 
    build: .
    ports:
      - "80:8080"
    depends_on:
      - db    
    environment:
      - DATABASE_URL=postgres://root:password@db:5432/database     
  db:
    image: postgres   
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - postgresdb:/var/lib/postgresql/data
     
volumes:
  postgresdb:
